package databindingtest;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.root.build_model.data.FavourMusics;
import com.example.root.build_model.data.MusicFile;
import databindingtest.User;

import databindingtest.FavourMusicsDao;
import databindingtest.MusicFileDao;
import databindingtest.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favourMusicsDaoConfig;
    private final DaoConfig musicFileDaoConfig;
    private final DaoConfig userDaoConfig;

    private final FavourMusicsDao favourMusicsDao;
    private final MusicFileDao musicFileDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favourMusicsDaoConfig = daoConfigMap.get(FavourMusicsDao.class).clone();
        favourMusicsDaoConfig.initIdentityScope(type);

        musicFileDaoConfig = daoConfigMap.get(MusicFileDao.class).clone();
        musicFileDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        favourMusicsDao = new FavourMusicsDao(favourMusicsDaoConfig, this);
        musicFileDao = new MusicFileDao(musicFileDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(FavourMusics.class, favourMusicsDao);
        registerDao(MusicFile.class, musicFileDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        favourMusicsDaoConfig.clearIdentityScope();
        musicFileDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public FavourMusicsDao getFavourMusicsDao() {
        return favourMusicsDao;
    }

    public MusicFileDao getMusicFileDao() {
        return musicFileDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
